apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-v0wp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-v0wp
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-v0wp
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-v0wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-v0wp
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-oqjp-tenant/appstudio/dc-metro-map-v0wp@sha256:5f45a1bce1b1960df4aecd14a32b52bf5f59372b5df5282e666adbdbbae11ee1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
